### ISSUE TITLE
Request: support Animated PNG (APNG)

### ISSUE THREAD

**Issue by bean-z** [woelper/oculante#305]
**Is your feature request related to a problem? Please describe.**
Animated PNG ([APNG](https://wiki.mozilla.org/APNG_Specification)) is an extension of PNG and uses the same file extension (.png) and MIME type (image/png). An example APNG is [a bouncing ball animation](https://en.wikipedia.org/wiki/File:Animated_PNG_example_bouncing_beach_ball.png) by Holger Will. The `zune-png` crate that Oculante uses doesn't support APNG.

**Describe the solution you'd like**
I would like to open APNG files as if they were GIF files. The `png` crate (([docs](https://docs.rs/png/latest/png/) and [crate page](https://crates.io/crates/png)) seems to be [about as fast](https://github.com/image-rs/image-png/discussions/416#discussioncomment-8131529) as `zune-png` now.

**Comment by woelper** [comment]
Thanks! Great idea! Do you happen to know what is required to know if a PNG is animated? The extension is the same as PNG, so I guess some pre-check for animation would need to be done.

**Comment by woelper** [comment]
Thanks! Great idea! Do you happen to know what is required to know if a PNG is animated? The extension is the same as PNG, so I guess some pre-check for animation would need to be done.

**Comment by bean-z** [comment]
The way that the `png` [docs](https://docs.rs/png/latest/png/#using-the-decoder) demonstrate is creating a Decoder, calling the `read_info()` method (which returns a Reader), and passing a mutable reference to a `vec!` buffer into the Reader's [`next_frame()`](https://docs.rs/png/0.17.13/png/struct.Reader.html#method.next_frame) method. I think it works like this: If there is only one frame (i.e. not APNG) then the first `next_frame()` call will return a struct of type `OutputInfo` (and put the image bytes into the buffer) and a second call will return an enum of type `DecodingError` of the variant `Format(FormatError)`.

**Comment by woelper** [comment]
Thanks!

It seems that `zune_png` supports apng, it just needs manual handling. I have made a branch that successfully decodes the sample animation you linked (thank you for such a well-written feature request by the way!). I'll test this a bit more and release.

**Comment by woelper** [comment]
I've found one animation that looks like the offset is incorrectly calculated here:
http://littlesvr.ca/apng/images/clock.png
I am using https://docs.rs/zune-png/latest/zune_png/fn.post_process_image.html to do post processing, so the bug is likely there, or in the image itself. All other examples decoded correctly as far as I could see.

**Comment by woelper** [comment]
I've released `v0.8.18` with APNG support now. Please let me know if this works as expected. Thank you again for this request.

**Comment by bean-z** [comment]
The [bouncing ball animation](https://commons.wikimedia.org/wiki/File:Animated_PNG_example_bouncing_beach_ball.png) has a minor visual artifact when displayed in Oculante. Here's a recording of Oculante on the left and Brave (a Chromium-based browser) on the right:

https://github.com/woelper/oculante/assets/143631489/425fb96b-4fcc-4eaf-9d6f-85938ed429dd

From what I can tell, Oculante correctly displays [this brain scan animation](https://en.wikipedia.org/wiki/File:Brain_MRI_apng_105px_100ms.png) and [this elephant animation](https://apng.onevcat.com/demo/).

**Comment by woelper** [comment]
Well spotted! 

This seems like to be an issue in zune_png. I've made a minimal example based on their example to decode an animation here:

https://github.com/woelper/apng_test

**Comment by woelper** [comment]
I have added an issue here:

https://github.com/etemesi254/zune-image/issues/185

**Comment by woelper** [comment]
I've merged the latest rc from zune-png and all examples look correct now.

**Comment by bean-z** [comment]
Version 0.8.22 can open the [clock](http://littlesvr.ca/apng/images/clock.png) and the [MRI scan](https://en.wikipedia.org/wiki/File:Brain_MRI_apng_105px_100ms.png) images, but I get a crash if I try to open the [bouncing ball](https://en.wikipedia.org/wiki/File:Animated_PNG_example_bouncing_beach_ball.png) or the [elephant](https://apng.onevcat.com/demo/).

I got a log in my terminal by running /Applications/oculante.app/Contents/MacOS/oculante with the environment variable `RUST_BACKTRACE=1`. First I dragged the MRI scan image into the app. Then I dragged in the bouncing ball.

```
[2024-05-20T02:04:53Z INFO  oculante::image_loader] Image is animated
[2024-05-20T02:05:04Z INFO  oculante::image_loader] Image is animated
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zune-png-0.5.0-rc1/src/apng.rs:269:28:
range end index 400 out of range for slice of length 100
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Richardn2002** [comment]
Same here
```
thread '<unnamed>' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zune-png-0.5.0-rc1/src/apng.rs:269:28:
range end index 4400 out of range for slice of length 1000
```
File in question attached.
![Richardn](https://github.com/woelper/oculante/assets/8529852/e7a203f0-b389-49f1-aca0-27d9ac201f0e)

**Comment by woelper** [comment]
I've opened an issue here:
https://github.com/etemesi254/zune-image/issues/210

**Comment by Stoppedpuma** [comment]
The crash has been fixed upstream! This will be included in the next release of Oculante and has been included at #739.
